# Generated by Django 6.0 on 2025-12-19 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('punch_time', models.DateTimeField(auto_now_add=True)),
                ('upper_body_image', models.ImageField(upload_to='attendance/upper/')),
                ('full_body_image', models.ImageField(upload_to='attendance/full/')),
                ('location_text', models.CharField(max_length=255)),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SELF_VERIFIED', 'Self Verified'), ('PENDING_ADMIN', 'Pending Admin'), ('ADMIN_VERIFIED', 'Admin Verified'), ('REJECTED', 'Rejected')], max_length=20)),
                ('verified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualcheck.employee')),
            ],
        ),
    ]
