# Generated by Django 6.0 on 2025-12-19 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualcheck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='full_body_image',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='upper_body_image',
        ),
        migrations.AddField(
            model_name='attendance',
            name='full_body_image_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='upper_body_image_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
